/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reloj.v;

import java.awt.BorderLayout;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author SOFIA RUDAS
 */
public class PanelReloj extends javax.swing.JPanel implements Runnable {

    private JLabel relojLabel;
    private SimpleDateFormat formato;
    
    public PanelReloj() {
        setLayout(new BorderLayout());
        relojLabel = new JLabel();
        relojLabel.setFont(new Font("Arial", Font.BOLD, 30));
        relojLabel.setHorizontalAlignment(SwingConstants.CENTER);
        add(relojLabel, BorderLayout.CENTER);

        formato = new SimpleDateFormat("hh:mm:ss a");

        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        while (true) {
            Date ahora = new Date();
            relojLabel.setText(formato.format(ahora));

            try {
                Thread.sleep(1000); 
            } catch (InterruptedException e) {
                break;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
