/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package comegalletas.v;

import comegalletas.ComeGalletas;
import comegalletas.Galleta;
import comegalletas.GraphicContainer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author SOFIA RUDAS
 */
public class Garden extends javax.swing.JPanel implements GraphicContainer {

    private ArrayList<Galleta> galletas;
    private ComeGalletas comegalletas;
    
    public Garden() {
        setPreferredSize(new Dimension(600, 400));
        setBackground(Color.GREEN);

        galletas = new ArrayList<>();

        for (int i = 0; i < 5; i++) {
            int x = (int) (Math.random() * 550);
            int y = (int) (Math.random() * 350);
            Galleta g = new Galleta(x, y, 20, 20);
            g.setGraphicContainer(this);
            galletas.add(g);
        }
        
        comegalletas = new ComeGalletas(50, 50, 30, 30, galletas);
        comegalletas.setColor(Color.BLUE);
        comegalletas.setGraphicContainer(this);

        Thread t = new Thread(comegalletas);
        t.start();

        Timer timer = new Timer(50, e -> repaint());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        for (Galleta galleta : galletas) {
            galleta.draw(g);
        }

        comegalletas.paint(g);
    }
    
    @Override
    public void refresh() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Rectangle getBoundaries() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
